// Code generated by Kitex v0.12.1. DO NOT EDIT.

package ragservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
	rag_svr "server/service/rag_svr/kitex_gen/rag_svr"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Test": kitex.NewMethodInfo(
		testHandler,
		newTestArgs,
		newTestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	ragServiceServiceInfo                = NewServiceInfo()
	ragServiceServiceInfoForClient       = NewServiceInfoForClient()
	ragServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return ragServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return ragServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return ragServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RagService"
	handlerType := (*rag_svr.RagService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rag_svr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func testHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(rag_svr.TestReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(rag_svr.RagService).Test(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *TestArgs:
		success, err := handler.(rag_svr.RagService).Test(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*TestResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newTestArgs() interface{} {
	return &TestArgs{}
}

func newTestResult() interface{} {
	return &TestResult{}
}

type TestArgs struct {
	Req *rag_svr.TestReq
}

func (p *TestArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(rag_svr.TestReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *TestArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *TestArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *TestArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *TestArgs) Unmarshal(in []byte) error {
	msg := new(rag_svr.TestReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var TestArgs_Req_DEFAULT *rag_svr.TestReq

func (p *TestArgs) GetReq() *rag_svr.TestReq {
	if !p.IsSetReq() {
		return TestArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *TestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TestArgs) GetFirstArgument() interface{} {
	return p.Req
}

type TestResult struct {
	Success *rag_svr.TestRsp
}

var TestResult_Success_DEFAULT *rag_svr.TestRsp

func (p *TestResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(rag_svr.TestRsp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *TestResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *TestResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *TestResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *TestResult) Unmarshal(in []byte) error {
	msg := new(rag_svr.TestRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *TestResult) GetSuccess() *rag_svr.TestRsp {
	if !p.IsSetSuccess() {
		return TestResult_Success_DEFAULT
	}
	return p.Success
}

func (p *TestResult) SetSuccess(x interface{}) {
	p.Success = x.(*rag_svr.TestRsp)
}

func (p *TestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TestResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Test(ctx context.Context, Req *rag_svr.TestReq) (r *rag_svr.TestRsp, err error) {
	var _args TestArgs
	_args.Req = Req
	var _result TestResult
	if err = p.c.Call(ctx, "Test", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
