services:
  redis-node:
    image: redis:8.0.2
    container_name: redis-node
    command: redis-server --port 6379 --cluster-announce-bus-port 16379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    network_mode: host
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-node-2:
    image: redis:8.0.2
    container_name: redis-node-2
    command: redis-server --port 6380 --cluster-announce-bus-port 16380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    network_mode: host
    volumes:
      - redis_data_2:/data
    restart: unless-stopped

  redis-node-3:
    image: redis:8.0.2
    container_name: redis-node-3
    command: redis-server --port 6381 --cluster-announce-bus-port 16381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    network_mode: host
    volumes:
      - redis_data_3:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  redis_data_2:
    driver: local
  redis_data_3:
    driver: local