services:
  api_gateway:
    build:
      context: ../..
      dockerfile: server/api_gateway/Dockerfile
    container_name: api_gateway
    ports:
      - "8081:8081"
    volumes:
      - /app/logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - ETCD_ENDPOINTS=10.1.20.17:2379,10.1.20.17:2381,10.1.20.17:2383
    restart: always
    network_mode: host

  rag_svr:
    build:
      context: ../..
      dockerfile: server/service/rag_svr/Dockerfile
    container_name: rag_svr
    ports:
      - "8888:8888"
    volumes:
      - /app/logs:/app/logs
    environment:
      - ETCD_ENDPOINTS=10.1.20.17:2379,10.1.20.17:2381,10.1.20.17:2383
      - TZ=Asia/Shanghai
    restart: unless-stopped
    network_mode: host

networks:
  jarvis_net:
    driver: bridge 