version: '3'

services:
  rag_svr:
    build:
      context: .                # 构建上下文，使用当前目录
      dockerfile: Dockerfile    # 指定使用的 Dockerfile
    container_name: rag_svr     # 容器名称
    ports:
      - "8888:8888"            # 端口映射，格式：主机端口:容器端口
    environment:
      - ETCD_ENDPOINTS=106.55.197.49:2379,106.55.197.49:2381,106.55.197.49:2383  # etcd 服务地址
    restart: unless-stopped     # 容器退出时自动重启，除非手动停止
    networks:
      - jarvis_net             # 使用的网络

networks:
  jarvis_net:                  # 定义网络
    driver: bridge             # 使用 bridge 驱动 