// Code generated by hertz generator.

package api_gateway

import "github.com/cloudwego/hertz/pkg/app"

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _test2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _knowledgeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addknowledgeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchknowledgeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _endsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chat0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatstreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _documentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchdocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedocumentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _memoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addmemoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmemoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletememoryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchmemoriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addchatrecordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recordsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchatrecordsMw() []app.HandlerFunc {
	// your code...
	return nil
}
