// Code generated by hertz generator.

package api_gateway

import "github.com/cloudwego/hertz/pkg/app"

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _test2Mw() []app.HandlerFunc {
	// your code...
	return nil
}
